### ISSUE TITLE
i receive notification that time slot appread, but when i open safari no time slot available

### ISSUE THREAD

**Issue by fred0z** [araavp/instacart-delivery-slot-finder#1]
it happens 5 times today, this script doesnt like amazon one will auto populate safari page once time slot found. i need to manually open safari page, and it still show me no time slot available. can you please fix?

**Comment by araavp** [comment]
I'm not sure if I understand what you're trying to ask. This script only works with Instacart. Is there a way you can try to show me what the Instacart delivery page says when the script detects a slot is available?

**Comment by fred0z** [comment]
i only use with instacart. this script send me notification five times saying detected time slot appeared, but when i open instacart immediately, not seeing any time slot.

**Comment by araavp** [comment]
What does the Instacart website show when you open it? Does it show the delivery part of the checkout and read "No delivery times available" or does it show a different message?

**Comment by fred0z** [comment]
it show the delivery part of the checkout and read "No delivery times available"  when i received time slot found notification from script

**Comment by araavp** [comment]
Did you make sure that “Allow JavaScript from Apple Events” is enabled on Safari? Do you see exactly this message or something slightly different? 
<img width="701" alt="Screen Shot 2020-04-15 at 12 47 44 AM" src="https://user-images.githubusercontent.com/52441902/79673845-33a6d000-8192-11ea-9acf-7b9a8bc54538.png">

**Comment by fred0z** [comment]
yes, i enable "Allow JavaScript from Apple Events". yup, same message in your screenshot

**Comment by araavp** [comment]
Okay, I'm working on a fix. I will comment again on this thread when you can redownload.

**Comment by fred0z** [comment]
sure, thanks. if possible could you do fix that when time slot appeared it will automatically open safari and show you instacart page and i can choose immortality.

i have been using whole food script, it will work it that way, which is super convenient.

thank you for your hard work, really appreciated.

**Comment by araavp** [comment]
Go ahead and redownload the script and let me know if the same error persists. Please also let me know if the error is fixed, so I can close this issue.

**Comment by fred0z** [comment]
![image](https://user-images.githubusercontent.com/62672278/79677051-c8252880-81ba-11ea-9e78-78a1be5aecf4.png)

i still seeing this when script notify me time slot appeared.

**Comment by araavp** [comment]
Thank you for your patience. Please redownload the latest version as of 4/18/20 6:35 PM PST. If the error continues or fixes, please let me know.

**Comment by fred0z** [comment]
I am able to place order with new script. Thank you so much.
