### ISSUE TITLE
error "The variable input is not defined." number -2753 from "input"

### ISSUE THREAD

**Issue by JRKelly** [araavp/instacart-delivery-slot-finder#2]
Re-downloaded and relaunched the new copy three separate times but still same error after about 5 min.

**Comment by JRKelly** [comment]
Not running Catalina, if that matters.

**Comment by araavp** [comment]
Thank you for reporting this issue. I have updated the file with a solution; please let me know if the problem persists. Also, please let me know if this problem is fixed, so I can close this issue.

**Comment by araavp** [comment]
If you receive a notification that a delivery slot is available, but Instacart displays "No delivery times available", please redownload to Version #6. If the error persists, please let me know

**Comment by JRKelly** [comment]
Seems better.  I don't know whether it found an opening in the night, but it ended with the credits instead of the error report, and I did get a slot when I checked this morning.  Thanks, nice process.
